### ISSUE TITLE
to-do list

### ISSUE THREAD

**Issue by mAKEkr** [mAKEkr/vuepress-theme-typewriter#2]
- [ ] remove @vuepress/plugin-google-analytics
- [ ] improve rss icon
- [ ] more obvious documentation
- [ ] frontmatter(categories/tag) page design and combined layout
